game:
  build: .
  restart: always
  command: "npm start"
  volumes:
    - .:/usr/src/app

nginx:
  image: nginx
  restart: always
  volumes:
   - ./nginx.conf:/etc/nginx/conf.d/default.conf
   - ./public:/nginx/html:ro
   - /etc/letsencrypt/live/example.com/cert.pem:/etc/ssl/certs/cert.pem
   - /etc/letsencrypt/live/example.com/fullchain.pem:/etc/ssl/certs/fullchain.pem
   - /etc/letsencrypt/live/example.com/privkey.pem:/etc/ssl/private/privkey.pem
   - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
  ports:
   - "443:443"
   - "80:80"
  links:
    - game
