module.exports = {
  story: {
    title: 'Raconteur',
    subtitle: 'Ghost Writers',
    description: 'Players contribute one line at a time to a story they only know the last line to.',
    minPlayers: 3,
    maxPlayers: 0,
    playTime: '10-15m',
    config: {
      numStories: {
        name: 'Number of Stories',
        type: 'int',
        min: 1,
        max: 0,
        defaults: '#numPlayers',
      },
      numRounds: {
        name: 'Number of Rounds',
        type: 'int',
        min: 1,
        max: 0,
        defaults: '#numRounds',
      },
    },
  },
  draw: {
    title: 'Scribble',
    subtitle: 'Drawing Conclusions',
    decription: 'Players will alternate between drawing and describing the previous rounds\' output.',
    minPlayers: 2,
    maxPlayers: 0,
    playTime: '10-15m',
    config: {
      numRounds: {
        name: 'Number of Rounds',
        type: 'int',
        min: 1,
        max: 0,
        defaults: '#numRounds',
      },
    },
  },
  assassin: {
    title: 'Wurderer',
    subtitle: 'Murdered by Words',
    description: 'Players are each given a target and a word they need to get their targets to say.',
    minPlayers: 2,
    maxPlayers: 0,
    playTime: '4+hr',
    config: {
      numRounds: {
        name: 'Number of Words',
        type: 'int',
        min: 1,
        max: 5,
        defaults: 2,
      },
    },
  },
  locations: {
    title: 'Underground',
    subtitle: 'Where are you?',
    description: 'One hidden player is trying to figure out where everyone is while avoiding other players\' questioning.',
    minPlayers: 3,
    maxPlayers: 10,
    playTime: '10m',
    config: {
      locationSet: {
        name: 'Location Set',
        type: 'list',
        listType: 'string',
        options: [{
          name: 'campus',
          text: 'Campus Life',
          value: [
            'Atrium',
            'Basketball Gym',
            'Bowling Alley',
            'Cafe',
            'Chemistry Lab',
            'Classroom',
            'Commons',
            'Dorm',
            'Electrical Closet',
            'Faculty Office',
            'Frat House',
            'Lawn',
            'Library',
            'Machine Shop',
            'Music Room',
            'Nurse\'s Office',
            'Parking Lot',
            'Patio',
            'Police Station',
            'Sports Field',
            'Statue',
            'Swimming Pool',
            'Theatre',
            'Weights Gym',
          ],
        }],
        default: 'campus'
      },
    },
  },
};